apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  selector:
    app: kubernetes-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31855