apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tests
  name: pod-tester
rules:
- apiGroups: [""] # indicates core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]